### PR TITLE
Dev variation with xdebug support

### PR DESCRIPTION
**Pull request by zaporylie**

### CODE REVIEW

**Comment by slashrsm** [comment]
Great addition. Could we also add variant with fpm?

**Comment by slashrsm** [comment]
Would be great to add ini configuration for dev environments  too (error_reporting, display_errors, ...). 

Would probably also make sense to also re-evaluate opcache settings (specially opcache.revalidate_freq).

**Comment by zaporylie** [comment]
> Would be great to add ini configuration for dev environments too (error_reporting, display_errors, ...).
> Would probably also make sense to also re-evaluate opcache settings (specially opcache.revalidate_freq).

:+1: 

> Could we also add variant with fpm?

Generally - sure, why not. I will consider it for sure. The only "problem" I see is that both fpm and xdebug use the same port by default, but we could change default port for xdebug.

**Comment by slashrsm** [comment]
> Generally - sure, why not. I will consider it for sure. The only "problem" I see is that both fpm and xdebug use the same port by default, but we could change default port for xdebug.

Sure, that should work.

**Pull request closed without merging**
