### PR TITLE
Add php 7.3

### PR DESCRIPTION
**Pull request by eiriksm**

### CODE REVIEW

**Comment by eiriksm** [comment]
Anything else you need for this? ;)

**Comment by zaporylie** [comment]
Just some time to have a look. I'll try to push it forward this evening.

**Comment by eiriksm** [comment]
🙏

**Comment by zaporylie** [comment]
Would be nice to get https://github.com/drupal-docker/php/tree/dev-2.x updated as well :) If you don't have time or need for it I'll make sure to do that sometime in the following days.

**Comment by eiriksm** [comment]
Don't need it personally, but I may find time to do a pr anyway :)

**Pull request merged**
