### PR TITLE
Add Redis to 7-fpm image.

### PR DESCRIPTION
**Pull request by slashrsm**
Adding Redis to 7-fpm. I am happy to add it to other images if needed.

### CODE REVIEW

**Comment by slashrsm** [comment]
Related to #28

**Comment by zaporylie** [comment]
> pecl/redis requires PHP (version >= 5.2.0, version <= 6.0.0, excluded versions: 6.0.0), installed version is 7.0.6

**Comment by slashrsm** [comment]
Redis extension needs to be build manually for PHP 7 it seems. Did that and added it to other php versions too. Also rebased against master. Let's see what Travis thinks about it now.

**Comment by zaporylie** [comment]
I decided to merge it into master however I am still a little bit concerned about maintaining additional extension, especially with no stable release. I would like to add to README file information about all the features supported by php image (i.e. redis) and information about maintenance status (i.e. redis - experimental).

I believe we should use pecl for phpredis/php7 ASAP (according to phpredis issue queue extension should be released soon™).

**Comment by slashrsm** [comment]
> I decided to merge it into master however I am still a little bit concerned about maintaining additional extension, especially with no stable release. I would like to add to README file information about all the features supported by php image (i.e. redis) and information about maintenance status (i.e. redis - experimental).

Sure. Let's do that. If I find any time in the next few days I'll start working on this and create a pull.

> I believe we should use pecl for phpredis/php7 ASAP (according to phpredis issue queue extension should be released soon™).

Agreed. 

Thank you for merging!

**Comment by zaporylie** [comment]
> Sure. Let's do that. If I find any time in the next few days I'll start working on this and create a pull.

Great! 

> Thank you for merging!

Thank you!

**Pull request merged**
