### PR TITLE
Create alpine images for dev + add some changes that were recently added to non-dev images

### PR DESCRIPTION
**Pull request by slashrsm**

### CODE REVIEW

**Comment by slashrsm** [comment]
It seems that xdebug doesn't support 7.1 yet. Removing for now. Should be green after this change.

**Comment by slashrsm** [comment]
Finally green. When This is merged I'll do the same for drush images.

**Comment by slashrsm** [comment]
@zaporylie Are you at DrupalCon?

**Comment by zaporylie** [comment]
@slashrsm No, I am not 😞 

Before you go to Drush could you look at #58 first? Main goal is to simplify repo structure and share config files across Dockerfiles

**Review by zaporylie — APPROVED** [review]
I fixed typo in README. Waiting for Travis to finish its job and this can be merged.

**Comment by slashrsm** [comment]
Great! I guess we should do #58 for dev too.

**Comment by zaporylie** [comment]
Already did it: #59

**Pull request merged**
